app:
  name: BankingApp
  version: 1.0.0
server:
  port: 8080
  host: 127.0.0.1
  apikey: arierimbaboemi
database:
  user: root
  password: Purw0Kert@
  host: localhost
  port: 3306
  name: banking_service
  driver: mysql
